apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - signalling.thinkmay.net
    - slavemanager.thinkmay.net
    - database.thinkmay.net
    - conductor.thinkmay.net
    - document.thinkmay.net
    - thinkmay.net
    - service.thinkmay.net
    - admin.thinkmay.net
    secretName: secret-tls
  rules:
  - host: conductor.thinkmay.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: conductor
            port:
              number: 80

  #
  - host: signalling.thinkmay.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: signalling
            port:
              number: 80


  - host: slavemanager.thinkmay.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: slavemanager
            port:
              number: 80

  - host: document.thinkmay.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: document
            port:
              number: 80

  - host: thinkmay.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: landing-page
            port:
              number: 80

  - host: service.thinkmay.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-page
            port:
              number: 80

  - host: admin.thinkmay.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: admin-page
            port:
              number: 80

  - host: database.thinkmay.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dbmanager
            port:
              number: 80