apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /Slave
        pathType: Prefix
        backend:
          service:
            name: slavemanager
            port:
              number: 80

      - path: /swagger/slavemanager.html
        pathType: Prefix
        backend:
          service:
            name: slavemanager
            port:
              number: 80
  #
      - path: /Signalling
        pathType: Prefix
        backend:
          service:
            name: signalling
            port:
              number: 80


  #
      - path: /database
        pathType: Prefix
        backend:
          service:
            name: systemdb
            port:
              number: 5432

  #
      - path: /Account
        pathType: Prefix
        backend:
          service:
            name: conductor
            port:
              number: 80

      - path: /src
        pathType: Prefix
        backend:
          service:
            name: resources
            port:
              number: 80

      - path: /stun
        pathType: Prefix
        backend:
          service:
            name: coturn
            port:
              number: 80