apiVersion: v1
kind: Service
metadata:
  name: admin-page
  namespace: frontend
  labels:
    app: admin-page
spec:
  type: ClusterIP
  ports:
  - port: 80    
  selector:
   app: admin-page
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-page
  namespace: frontend
spec:
  selector:
    matchLabels:
      app: admin-page
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: admin-page
    spec:
      containers:
      - name: admin-page
        image: pigeatgarlic/admin-page:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "300Mi"
            cpu: "300m"
        ports:
        - containerPort: 80