
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: huyhoangdo0205@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class:  traefik
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: le-crt
spec:
  secretName: tls-secret
  issuerRef:
    kind: Issuer
    name: letsencrypt
  commonName: thinkmay.net
  dnsNames:
    - thinkmay.net
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect
  namespace: default
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect@kubernetescrd
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - thinkmay.net
    - host.thinkmay.net
    - database.thinkmay.net
    - resources.thinkmay.net
    - admin.thinkmay.net
    - service.thinkmay.net
    secretName: secret-tls
  rules:
  - host: conductor.thinkmay.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: conductor
            port:
              number: 80

  #
  - host: signalling.thinkmay.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: signalling
            port:
              number: 80


  - host: slavemanager.thinkmay.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: slavemanager
            port:
              number: 80
              
  - host: thinkmay.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: landing-page
            port:
              number: 80

  - host: service.thinkmay.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-page
            port:
              number: 80

  - host: admin.thinkmay.net
    http:
      paths:
      - path: /login
        pathType: Prefix
        backend:
          service:
            name: admin-page
            port:
              number: 80

  - host: database.thinkmay.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dbmanager
            port:
              number: 80
  - host: resources.thinkmay.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: resources 
            port:
              number: 80