apiVersion: v1
kind: Service
metadata:
  name: signalling
  labels:
    app: signalling
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"no-timeout"}}'
spec:
  type: ClusterIP
  ports:
   - port: 80
  selector:
   app: signalling
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signalling
spec:
  selector:
    matchLabels:
      app: signalling
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: signalling
    spec:
      containers:
      - name: signalling
        image: pigeatgarlic/signalling:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "300Mi"
            cpu: "300m"
        readinessProbe:
          httpGet:
            path: /swagger/index.html
            port: 80
        ports:
        - containerPort: 80