
apiVersion: v1
kind: Service
metadata:
  name: resource 
  labels:
    app: resource
spec:
  type: ClusterIP
  ports:
  - port: 80    
  selector:
   app: resource
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource
spec:
  selector:
    matchLabels:
      app: resource
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: resource
    spec:
      containers:
      - name: resource
        image: nginx
        resources:
          requests:
            memory: "300Mi"
            cpu: "300m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/usr/share/nginx/html/installer"
            name: installer
        
      volumes:
      - name: installer 
        persistentVolumeClaim:
          claimName: installer-volume-claim