apiVersion: v1
kind: Service
metadata:
  name: systemhub
  namespace: backend
  labels:
    app: systemhub
spec:
  type: NodePort
  ports:
  - port: 80    
  selector:
   app: systemhub
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: systemhub
  namespace: backend
spec:
  serviceName: systemhub
  replicas: 1
  selector:
    matchLabels:
      app: systemhub
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: systemhub
    spec:
      containers:
      - name: systemhub
        image: pigeatgarlic/systemhub:2022-02-17
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "700m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
        ports:
        - containerPort: 80
      nodeSelector:
        node.kubernetes.io/instance-type: t3.medium