FROM mcr.microsoft.com/dotnet/sdk:5.0 AS DOTNET
ENV PATH $PATH:/root/.dotnet/tools
RUN dotnet tool install -g dotnet-ef --version 5.0.1

WORKDIR /src

COPY . .

CMD ["sleep", "10000m"]

FROM ubuntu:latest AS UBUNTU

CMD ["sleep", "10000m"]