version: '3'


#personal cloud computing
services: 
#signalling service
  signalling:
    image: ${PCC_URL}:${REGISTRY_PORT}/signalling:latest 
    restart: always
    ports:
      - "82:80"


  conductor:
    image: ${PCC_URL}:${REGISTRY_PORT}/conductor:latest
    restart: always
    ports:
      - "81:80"


  slavemanager:
    image: ${PCC_URL}:${REGISTRY_PORT}/conductor:latest
    restart: always
    ports:
      - "83:80"


