version: '3'


#personal cloud computing
services: 
#signalling service
  signalling:
    image: ${PCC_URL}:${REGISTRY_PORT}/signalling:signalling_v1.0.0   
    restart: always


    environment: 
      - SLAVEMANAGER_SERVER=http://${PCC_URL}:81

    ports:
      - "82:80"

    depends_on: 
      - slavemanager 


  slavemanager:
    image: ${PCC_URL}:${REGISTRY_PORT}/slavemanager:slavemanager_v1.0.0    
    restart: always

    environment: 
      - SIGNALLING_SERVER=http://${PCC_URL}:82
      - FLUTTER_SERVER=http://${PCC_URL}:80

      - DATABASE_SERVER=${PCC_URL}
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_PORT=${DB_PORT}

    ports:
      - "81:80"
