apiVersion: v1
kind: Service
metadata:
  name: metric-collector
  labels:
    app: metric-collector
spec:
  type: NodePort
  ports:
  - port: 80    
  selector:
   app: metric-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-collector
spec:
  selector:
    matchLabels:
      app: metric-collector
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: metric-collector
    spec:
      containers:
      - name: metric-collector
        image: pigeatgarlic/metric-collector:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "300Mi"
            cpu: "300m"
        ports:
        - containerPort: 80