apiVersion: v1
kind: Service
metadata:
  name: systemhub
  namespace: development
  labels:
    app: systemhub
spec:
  type: NodePort
  ports:
  - port: 80    
  selector:
   app: systemhub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: systemhub
  namespace: development
spec:
  selector:
    matchLabels:
      app: systemhub
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: systemhub
    spec:
      containers:
      - name: systemhub
        image: pigeatgarlic/systemhub:development
        imagePullPolicy: Always
        resources:
          requests:
            memory: "400Mi"
            cpu: "200m"
          limits:
            memory: "500Mi"
            cpu: "400m"
        ports:
        - containerPort: 80