apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-volume
  labels:
    type: local
spec:
  storageClassName: fast
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/registry"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: installer-volume
  labels:
    type: local
spec:
  storageClassName: fast
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/installer"
