version: '3'


#personal cloud computing
services: 
#signalling service
  signalling:
    image: ${DOCKER_REGISTRY}/signalling:release-latest 
    restart: always
    ports:
      - "82:80"


  conductor:
    image: ${DOCKER_REGISTRY}/conductor:release-latest
    restart: always
    ports:
      - "81:80"


  slavemanager:
    image: ${DOCKER_REGISTRY}/slavemanager:release-latest
    restart: always
    ports:
      - "83:80"

