apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    pods: "10" 
    requests.cpu: "4" 
    requests.memory: 8Gi 
    requests.ephemeral-storage: 2Gi 
    limits.cpu: "4" 
    limits.memory: 8Gi 
    limits.ephemeral-storage: 4Gi