apiVersion: v1
kind: ConfigMap
metadata:
  name: dbmanager-config
  labels:
    app: dbmanager
data:
  PGADMIN_DEFAULT_EMAIL: admin@thinkmay.com
  PGADMIN_DEFAULT_PASSWORD: ASDFak!C#$%2351531c2c152
---
apiVersion: v1
kind: Service
metadata:
  name: dbmanager
  labels:
    app: dbmanager
spec:
  type: ClusterIP
  ports:
   - port: 80
  selector:
   app: dbmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbmanager
spec:
  selector:
    matchLabels:
      app: dbmanager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dbmanager
    spec:
      containers:
      - name: dbmanager
        image: dpage/pgadmin4
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "300Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "700m"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: dbmanager-config