apiVersion: apps/v1
kind: Deployment
metadata:
  name: development
  namespace: default
spec:
  selector:
    matchLabels:
      app: development
  replicas: 0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: development
    spec:
      containers:
      - name: development
        image: pigeatgarlic/host:development
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "700Mi"
            cpu: "700m"
      nodeSelector:
        node.kubernetes.io/instance-type: t3a.small