apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configuration
  labels:
    app: postgres
data:
  POSTGRES_DB: postgredb
  POSTGRES_USER: thinkmay 
  POSTGRES_PASSWORD: thinkmayvantue

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  labels:
    app: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
      - name: fix-volume
        image: busybox
        command: ["sh", "-c", "rm -rf /var/lib/postgresql/data/lost+found"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "150m"
      containers:
      - name: postgres
        image: postgres:latest
        envFrom:
        - configMapRef:
            name: postgres-configuration
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "3Gi"
            cpu: "1500m"
      volumes:
      - name: data
        awsElasticBlockStore:        
          volumeID: "vol-055163cce533c94fc"
          fsType: ext4
      nodeSelector:
        topology.kubernetes.io/zone: ap-southeast-1b
        node.kubernetes.io/instance-type: t3.medium
        
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
  type: ClusterIP 
  selector:
    app: postgres