apiVersion: v1
kind: Service
metadata:
  name: coturn
  labels:
    app: coturn
spec:
  type: ClusterIP
  ports:
   - port: 3478
  selector:
   app: coturn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: systemdb
spec:
  selector:
    matchLabels:
      app: systemdb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: coturn
    spec:
      containers:
      - name: systemdb
        image: coturn/coturn
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 3478