apiVersion: v1
kind: Service
metadata:
  name: resources
  labels:
    app: resources
spec:
  type: ClusterIP
  ports:
   - port: 80
  selector:
   app: resources
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources
spec:
  selector:
    matchLabels:
      app: resources
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: resources
    spec:
      containers:
      - name: resources
        image: pigeatgarlic/resources:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80