apiVersion: v1
kind: Service
metadata:
  name: service-page
  labels:
    app: service-page
spec:
  type: ClusterIP
  ports:
  - port: 80    
  selector:
   app: service-page
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-page
spec:
  selector:
    matchLabels:
      app: service-page
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: service-page
    spec:
      containers:
      - name: service-page
        image: pigeatgarlic/service-page:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80