apiVersion: v1
kind: Service
metadata:
  name: signalling
  labels:
    app: signalling
spec:
  type: ClusterIP
  ports:
   - port: 80
  selector:
   app: signalling
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signalling
spec:
  selector:
    matchLabels:
      app: signalling
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: signalling
    spec:
      containers:
      - name: signalling
        image: pigeatgarlic/signalling:release_latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80