apiVersion: v1
kind: Service
metadata:
  name: slavemanager
  labels:
    app: slavemanager
spec:
  type: ClusterIP
  ports:
   - port: 80
  selector:
   app: slavemanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slavemanager
spec:
  selector:
    matchLabels:
      app: slavemanager
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: slavemanager
    spec:
      containers:
      - name: slavemanager
        image: pigeatgarlic/slavemanager:release_latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80