#ifndef __EXIT_CODE_H__
#define __EXIT_CODE_H__

typedef enum
{
    UNKNOWN_ERROR,
    CORE_STATE_CONFLICT,
    SIGNALLING_SERVER_REGISTRATION_ERROR,
    SIGNALLING_SERVER_CONNECTION_ERROR,
    PIPELINE_ERROR,
    DATA_CHANNEL_ERROR,
    SESSION_DENIED,
    CORRUPTED_SESSION_INFORMATION,
    PLUGINS_MISSING
}ExitCode;

#endif