
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: backend
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2.3-alpine
        command: ["redis-server"]
        args: ["/etc/redis/redis.conf"]
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /etc/redis/
      volumes:
      - name: redis-config
        emptyDir: {}
      - name: config
        configMap:
          name: redis-config   
      - name: data
        awsElasticBlockStore:        
          volumeID: "vol-046dcf4ee77ff68ae"
          fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: backend
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: redis
