apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logging-volume-claim
spec:
  storageClassName: csi-sc
  resources:
    requests:
      storage: 30Gi
  accessModes:
    - ReadWriteMany
---
kind: StorageClass
apiVersion: storage.k8s.io/v1 
metadata:
  name: csi-sc 
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
fileSystemId: ext4