apiVersion: v1
kind: PersistentVolume
metadata:
  name: systemdb-volume
  labels:
    type: local
spec:
  storageClassName: fast
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logging-volume
  labels:
    type: local
spec:
  storageClassName: fast
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/logging"
