
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: backend
  annotations:
    kubernetes.io/ingress.class: nginx

spec:
  rules:
  - host: host.thinkmay.net
    http:
      paths:
      - path: /User
        pathType: Prefix
        backend:
          service:
            name: conductor
            port:
              number: 80
      - path: /Session
        pathType: Prefix
        backend:
          service:
            name: conductor
            port:
              number: 80
      - path: /Device
        pathType: Prefix
        backend:
          service:
            name: conductor
            port:
              number: 80
      - path: /Shell
        pathType: Prefix
        backend:
          service:
            name: conductor
            port:
              number: 80

      - path: /Account
        pathType: Prefix
        backend:
          service:
            name: authenticator
            port:
              number: 80
  
      - path: /Handshake
        pathType: Prefix
        backend:
          service:
            name: signalling
            port:
              number: 80

      - path: /Agent
        pathType: Prefix
        backend:
          service:
            name: slavemanager
            port:
              number: 80

      - path: /Metric
        pathType: Prefix
        backend:
          service:
            name: metric-collector
            port:
              number: 80
              