apiVersion: v1
data:
  keyname: autoscaling
  privatekey: 
"PuTTY-User-Key-File-2: ssh-rsa
Encryption: none
Comment: autoscaling
Public-Lines: 6
AAAAB3NzaC1yc2EAAAADAQABAAABAQCaNwHT96CSADz/ZQHoDPUoqtGztg/hEEuQ
CABFrxszV2gRVBJVx6TloSzEjoNfwga8iaS/uIQlGwqvHcSJSYRfimpG2OrwyyGt
UFf/qdAYLLkyQ411WEViwOv+cnWAUS/wUzvCzs2XrgTxLoY9k6ozHzKEwblWjsT3
e8cTMRjRRo23nxoK8/mH8XDMKNJ99Z0GJOj17oRZOQQMx7/h0yq2zLca5obn1vFr
A1xSierdJsktu2b75MhKzqQQJKVf3lMwGUHKf80NstCb5OmWPKNLoSFEQNUwWn47
IREd58S/64NB/ApeI5inXKJh5a5tJUUF/m26av+9u5TKo6FA/gwF
Private-Lines: 14
AAABADWi8CXTOKvPHWgOr40QBKyyTOFeb0NuMXnU7pNOBf3jZrSwMvhWycl8N1/d
2V+S0lj83qo3+O4W665gghzlzv6T28bsZzp8zCfFi/XGEDR4SalryWWI4Akq5GnJ
UYjhs/S4Xk6xMtyQj/N6pQIBu+6v6Rg3cMjkOymAiYrpRqJyhL5HarAIGeHZ77yg
fPBIdJYjR0p038AIVHW5Go1B+gy/ZBZMJl5RxmRGBaPFedjL1ZEswAyjCTJF+9/L
nBjULbdnlPhBPhH6r7SpMV+556nE3t0izQxySMARwt7T1Xd4Afo+jfY8v9gYd0me
pQ/gD+MWo9J8ab+WAjkBxquFpgEAAACBAPFT8hFKaMxeF9xCsttFuRQU2BCT9z5n
GEAO/C5KNPgCS9bU/ue83XVMQVFHYa3mcjE2yyZZxbJhpFaHOqVOmE8QU2gAuzUL
ArdgPTAe3JKDB0OS37Ixa/Ij/E8AS7O+mPLn5r0JR6kOUxFkx62uZsF7TRs6t9St
CKDdEcSQcpHBAAAAgQCjlzl6gZLcAjTZITY+6O4FMiwOm+qI8J9ELoUxKJrE5wbg
EwxLeBANHLWT4n0DozHzQvJOI84cnLxwdz4CcYryLn5ODbaYpe7+7/KuEVaX60EF
ft21i/TBeo4MwB1azQOpMSyAyHxb5nuodes7I/2RRo8xMopDH0HWCsU8hUeDRQAA
AIEAlIXbINB/V0/rYrJb82tzERgjdINvHi/j3XTDAxFocy/4909KXsoP1Y6TdpCT
XtaB4GnS1eObzc78u8Msr7xuv5AQmaBfPWiN0/59nUG2kC2gd98Z6HSJ3c0o4tZv
SfshUEZHj05mPg3mOQWV1RlgyfjQ/RnnHZQ5ectpHIAAz6c=
Private-MAC: 6c211e914546ed40ebcba379b1db7d7e43ec8724"

kind: Secret
metadata:
  name: mysecret
  namespace: default
