version: "3.3"
    
services:
  workermanager:
    container_name: cluster_manager
    image: pigeatgarlic/workermanager:${MANAGER_VERSION}
    environment:
      REDIS_IP: "cache"
      OWNER_TOKEN: ""
      CLUSTER_TOKEN: ""
    restart: unless-stopped
    ports:
      - "5000:80"


  cluster-ui:
    container_name: cluster_ui
    image: pigeatgarlic/cluster-ui:${UI_VERSION}
    restart: unless-stopped
    ports:
      - "8080:3000"

  cache:
    container_name: redis_cache
    image: redis:latest
    volumes:
       - /home/cache:/data
    restart: unless-stopped
