
apiVersion: v1
kind: Service
metadata:
  name: authenticator
  namespace: backend
  labels:
    app: authenticator
spec:
  type: NodePort
  ports:
  - port: 80    
  selector:
   app: authenticator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticator
  namespace: backend
spec:
  selector:
    matchLabels:
      app: authenticator
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: authenticator
    spec:
      containers:
      - name: authenticator
        image: pigeatgarlic/authenticator:2021-12-23
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500Mi"
            cpu: "300m"
          limits:
            memory: "700Mi"
            cpu: "500m"
        ports:
        - containerPort: 80