
apiVersion: v1
kind: Service
metadata:
  name: systemhub
  namespace: backend
  labels:
    app: systemhub
spec:
  type: NodePort
  ports:
  - port: 80    
  selector:
   app: systemhub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: systemhub
  namespace: backend
spec:
  selector:
    matchLabels:
      app: systemhub
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: systemhub
    spec:
      containers:
      - name: systemhub
        image: pigeatgarlic/systemhub:2021-12-22
        imagePullPolicy: Always
        resources:
          requests:
            memory: "700Mi"
            cpu: "9000m"
          limits:
            memory: "l000Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80