apiVersion: v1
kind: Service
metadata:
  name: document
  labels:
    app: document
spec:
  type: ClusterIP
  ports:
  - port: 80    
  selector:
   app: document
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: document
spec:
  selector:
    matchLabels:
      app: document
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: document
    spec:
      containers:
      - name: document
        image: pigeatgarlic/document:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80