version: '3'

services: 
  # database:
  #   image: DATABASEdb:latest

  #   environment:  
  #     MYSQL_ROOT_PASSWORD: "wesh0uldn0tuseThisPW"
  #     MYSQL_DATABASE: '${DB_NAME}' 
  #     MYSQL_USER: '${DB_USER}'
  #     MYSQL_PASSWORD: '${DB_PASSWORD}'

  #   restart: always
  #   ports: 
  #     - "1000:3306"
  #   volumes: 
  #     - /home/host/database:/var/lib/mysql
  #     - /home/host/dbconf:/etc/mysql 

  ngrok:
    iamge: shkoliar/ngrok:latest
    ports:
      - 4551:4551
    link: 
      -
  postgres:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_USER: "thinkmay"
        POSTGRES_PASSWORD: "thinkmayvantue"
        PGDATA: "/data/thinkdata"
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '1000:5432'
      volumes: 
        - /home/host/database:/data/postgres
        - /home/host/database/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  registry:
    image: registry
    restart: always

    volumes: 
      - '/home/host/registry:/var/lib/registry'
    ports:
      - "5000:5000"
      