name: CLIENT

on:
  push:
    branches: [ master ]
    paths: 
    - 'Client/website/**'
  pull_request:
    branches: [ master ]
    paths: 
    - 'Client/website/**'
  workflow_dispatch:

#setup environment variable
env:
  REGISTRY: ghcr.io
  SERVICE_PAGE_IMAGE:  ${{ secrets.DOCKER_USERNAME }}/service-page:latest
  LANDING_PAGE_IMAGE:  ${{ secrets.DOCKER_USERNAME }}/landing-page:latest
  ADMIN_PAGE_IMAGE:  ${{ secrets.DOCKER_USERNAME }}/admin-page:latest

  GKE_CLUSTER: thinkmay-cluster-v1  # TODO: update to cluster name
  GKE_ZONE: asia-southeast1-a   # TODO: update to cluster zone
jobs:
  build-service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: ServicePage 
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: Client/website/service-page 
        push: true
        tags: ${{ env.SERVICE_PAGE_IMAGE }}

  build-landing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: LandingPage 
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: Client/website/landing-page
        push: true
        tags: ${{ env.LANDING_PAGE_IMAGE }}

  build-admin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: AdminPage 
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: Client/website/admin-page
        push: true
        tags: ${{ env.ADMIN_PAGE_IMAGE }}

      

  kubernetes-deployment:
    name: Kubernetes-server-deploy
    runs-on: ubuntu-latest
    needs: [build-admin, build-service, build-landing] 

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ../private.key
        sudo chmod 600 ../private.key
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      shell: bash
      env:
        SSH_KNOWN_HOSTS: thinkmay.net
        SSH_PRIVATE_KEY: ${{secrets.AWS_KEY}}
        SSH_KEY_PATH: ${{ github.workspace }}/../private.key


    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        ssh -i "$SSH_KEY_PATH" ubuntu@thinkmay.net
        sudo -i
        kubectl rollout restart deploy landing-page 
        kubectl rollout restart deploy service-page 
        kubectl rollout restart deploy admin-page 
      shell: bash
      env:
        SSH_KEY_PATH: ${{ github.workspace }}/../private.key