name: Deploy

on:
  workflow_dispatch:


#setup environment variable
env:
  REGISTRY: ghcr.io
  SIGNALLING_IMAGE_NAME:  ${{ secrets.DOCKER_USERNAME }}/signalling:latest
  SLAVEMANAGER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/slavemanager:latest
  CONDUCTOR_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/conductor:latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login to server using ssh
      - name: Deploy backbone container
        uses: appleboy/ssh-action@master
        with:
          username:  ${{ secrets.HOST_USERNAME }}
          host: ${{ secrets.HOST_IP }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            cd /home/ubuntu/ThinkMay/Deployment/Host
            docker-compose pull
            docker-compose up --detach

      # Login to server using ssh
      - name: Deploy host container
        uses: appleboy/ssh-action@master
        with:
          username:  ${{ secrets.HOST_USERNAME }}
          host: ${{ secrets.HOST_IP }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            cd /home/ubuntu/personal-cloud-computing/Deployment/Host
            docker-compose pull
            docker-compose up --detach