name: Deploy

on:
  workflow_dispatch:

jobs:       
  deployment:
    runs-on: ubuntu-latest
    steps:
      # Login to server using ssh
      - name: Deploy backbone container
        uses: appleboy/ssh-action@master
        with:
          username:  ${{ secrets.HOST_USERNAME }}
          host: ${{ secrets.HOST_IP }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            cd /src
            git checkout master
            git pull https://${{ secrets.OAUTH_TOKEN }}@github.com/pigeatgarlic/personal-cloud-computing.git master
            cd /src/Deployment/backbone
            docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
            docker-compose pull
            docker-compose up --detach
            cd /src/Deployment/host-release
            docker-compose pull
            docker-compose up --detach