name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


#setup environment variable
env:
  REGISTRY: ghcr.io
  SIGNALLING_IMAGE_NAME:  ${{ secrets.DOCKER_USERNAME }}/signalling:latest
  SLAVEMANAGER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/slavemanager:latest
  CONDUCTOR_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/conductor:latest

jobs:
  dotnet-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # restore other dependencies of slavemanager and 
    - name: Restore dependencies on slavemanager
      shell: pwsh
      working-directory: Host/SlaveManager
      run: |
        dotnet restore .

    - name: Restore dependencies on signalling
      shell: pwsh
      working-directory: Host/Signalling
      run: |
        dotnet restore .

    - name: Restore dependencies on conductor
      shell: pwsh
      working-directory: Host/Conductor
      run: |
        dotnet restore .

    # Build signalling and slavemanager
    - name: Build signalling
      shell: pwsh
      working-directory: Host/Signalling
      run: |
        dotnet build .
        
    - name: Build slavemanager
      shell: pwsh
      working-directory: Host/SlaveManager
      run: |
        dotnet build .
    
    - name: Build conductor
      shell: pwsh
      working-directory: Host/Conductor
      run: |
        dotnet build .








