name: HOST_PRODUCTION

on:
  push:
    branches: [ master ]
    paths: 
    - 'Host/**'
  pull_request:
    branches: [ master ]
    paths: 
    - 'Host/**'
  workflow_dispatch:


  

jobs:      
  build-signalling:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: get current date
        id: date
        run: echo "::set-output name=date::$(date +'%y-%m-%d-%h')"

    - name: Signalling
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: Host  
        target: prod
        file: Host/Signalling/Dockerfile
        push: true
        tags: ${{ env.SIGNALLING_IMAGE_NAME }}
        env:
          SIGNALLING_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/signalling:${{ steps.date.outputs.date }}

  build-slavemanager:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: get current date
        id: date
        run: echo "::set-output name=date::$(date +'%y-%m-%d-%h')"

    - name: SlaveManager
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: Host  
        target: prod
        file: Host/SlaveManager/Dockerfile
        push: true
        tags: ${{ env.SLAVEMANAGER_IMAGE_NAME }}
        env:
          SLAVEMANAGER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/slavemanager:${{ steps.date.outputs.date }}

  build-conductor:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: get current date
        id: date
        run: echo "::set-output name=date::$(date +'%y-%m-%d-%h')"

    - name: Conductor
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: Host 
        target: prod
        file: Host/Conductor/Dockerfile
        push: true
        tags: ${{ env.CONDUCTOR_IMAGE_NAME }}
        env:
          CONDUCTOR_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/conductor:${{ steps.date.outputs.date }}


  build-authenticator:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: get current date
        id: date
        run: echo "::set-output name=date::$(date +'%y-%m-%d-%h')"

    - name: Authenticator 
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: Host 
        target: prod
        file: Host/Authenticator/Dockerfile
        push: true
        tags: ${{ env.AUTHENTICATOR_IMAGE_NAME }}
        env:
          AUTHENTICATOR_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/authenticator:${{ steps.date.outputs.date }}

  build-metric-collector:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: get current date
        id: date
        run: echo "::set-output name=date::$(date +'%y-%m-%d-%h')"

    - name: MetricCollector
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: Host 
        target: prod
        file: Host/MetricCollector/Dockerfile
        push: true
        tags: ${{ env.METRIC_COLLECTOR_IMAGE_NAME }}
        env:
          METRIC_COLLECTOR_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/metric-collector:${{ steps.date.outputs.date }}