name: SYNC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]



jobs:     
  sync:
    runs-on: ubuntu-latest
    needs: [ build-conductor, build-slavemanager, build-signalling]
    steps:
    - name: Deploy on kubernetes
      uses: appleboy/ssh-action@master
      with:
        username:  ${{ secrets.HOST_USERNAME }}
        host: ${{ secrets.HOST_IP }}
        password: ${{ secrets.HOST_PASSWORD }}
        script: |
          cd /personal-cloud-computing
          git checkout master
          git pull https://${{ secrets.OAUTH_TOKEN }}@github.com/pigeatgarlic/personal-cloud-computing.git master